# Generated by Django 5.2.8 on 2025-12-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blogs.category'),
            preserve_default=False,
        ),
    ]
