# Generated by Django 5.2.8 on 2025-12-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
    ]
